config/routes.rb
Rails.application.routes.draw do
  resources :urls
  
  get '/:id' => 'urls#redi'
  
  get '/s/:randstr' => 'urls#redi2'

  root 'urls#index'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :get_url, only: [:show, :edit, :update, :destroy, :redi]
  
  #redirects based on integer (id)
  def redi
    addy = @url.link
    redirect_to "#{addy}"
  end
  
  #redirects based on random string
  def redi2
    @url = Url.find_by_randstr(params[:randstr])
    addy = @url.link
    redirect_to "#{addy}"
  end
  
  def index
    @urls = Url.all
  end
  
  
  def show
  end
  
  def new
    @url = Url.new
    g_randstr
    Url.all.each do |u|
      g_randstr while u[:randstr] == @url.randstr
    end
    @url.save
  end
  
  #generates a random string to put into @url.randstr
  def g_randstr
    @url.randstr = (0...4).map { ('a'..'z').to_a[rand(26)] }.join
  end
    

  def create
    @url = Url.new(url_params)
    
    if @url.save
      redirect_to @url, notice: 'Success!'
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @url.update(url_params)
      redirect_to @url, notice: "Success!"
    else
      render :edit
    end
  end

  def destroy
    @url.destroy
    redirect_to urls_path, notice: "BOOM! Destruction Complete"
  end
  
  
  private
  
  def get_url
    @url = Url.find(params[:id])
  end
  
  
  def url_params
    params.require(:url).permit(:link)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlNoScaff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_formmm.html.erb
<p> Don't even think about putting an invalid URL format or I'll stop you dead in your tracks! </p>

<%=form_for(@url) do |f|%>
  <% if @url.errors.any? %>
    <div id="err_explain">
      <h2><%= pluralize(@url.errors.count, "error")%> prevented this data from being saved:</h2>
      <ul>
        <% @url.errors.full_messages.each do |m| %>
          <li> <%= m %> </li>
          <%end%>
      </ul>
    </div>
  <%end%>
  
  <div class="field">
    <%= f.label 'Input an awesome URL:' %>
    <br>
    <%= f.url_field :link %>
  </div>
  <div class="actions">
    <%=f.submit 'Submit' %>
  </div>
<%end%>

app/views/urls/edit.html.erb
<h1> Haha you made a mistake. Re-do button activating... </h1>

<%= render 'formmm'%>

<br>

<%= link_to 'Cancel Re-do', urls_path%>

app/views/urls/index.html.erb
<p id="alerty"> <%= notice %> </p>

<h1> All URLs </h1>

<%=link_to 'Add new URL', new_url_path%>

  <br>

<table>
  <thead>
    <tr>
      <th> Link </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @urls.each do |u|%>
      <tr>
        <td> <%=u.link%> </td>
        <td> <%=link_to 'Show shortened URL', u%> </td>
        <td> <%= link_to 'Edit', edit_url_path(u)%> </td>
        <td> <%= link_to 'Delete', u, method: :delete, data: {confirm: "Positive?? There's no turning back after this."}%> </td>
      </tr>
    <%end%>
  </tbody>
  

  
  <!-- <% link_to 'Add a new URL', new_url_path %> -->
      

app/views/urls/new.html.erb
<h1> Welcome to URL Creation </h1>

<%= render 'formmm' %>

<br>

<%= link_to "Cancel", urls_path%>

app/views/urls/show.html.erb
<p id="alerty"> <%= notice %> </p>

<%= link_to 'Home', urls_path%>

<p> Your link is <%= @url.link %></p>

<p> You may now access your link by visiting <%= "localhost:3000/s/" + @url.randstr%> </p>

<p> OR Via:  <a href="<%=@url.link%>"><%= "localhost:3000/" + @url.id.to_s%></a> </p> 

<p>Don't believe me? Type it in manually and see for yourself!</p>